version: "2"
services:
  config-server:
    image: httpd:alpine
    ports:
      - "8000:80"
    volumes:
      - ${DIR}/config-server:/usr/local/apache2/htdocs:ro
  mysql:
    image: mysql:latest
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=666666
      - MYSQL_DATABASE=my_habitat
  mongo:
    image: mongo:latest
    expose:
      - "27017"
  keycloak-server:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  redis:
    image: redis:latest
    expose:
      - "6379"
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  logstash:
    image: logstash
    ports:
      - "12201:12201/udp"
    command: -e 'input { gelf { host => "0.0.0.0" port => 12201 } }
              output { elasticsearch { hosts => ["elasticsearch"] } }'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
      - logstash
    depends_on:
      - logstash
#  inventory-microservice:
#    image: my-habitat/inventory-microservice
#    links:
#      - config-server
#      - redis
#      - logstash
#    depends_on:
#      - config-server
#      - redis
#      - logstash
#    expose:
#      - "8086"
  device-microservice:
    image: my-habitat/device-microservice
    links:
      - mysql
      - logstash
    depends_on:
      - mysql
      - logstash
    expose:
      - "8082"
  account-microservice:
    image: my-habitat/account-microservice
    links:
      - mysql
      - logstash
    depends_on:
      - mysql
      - logstash
    expose:
      - "8081"
  room-microservice:
    image: my-habitat/room-microservice
    links:
      - mongo
      - logstash
    depends_on:
      - mongo
      - logstash
    expose:
      - "8085"
#  cache-infrastructure:
#    image: my-habitat/cache-infrastructure
#    links:
#      - redis
#      - logstash
#    depends_on:
#      - redis
#      - logstash
#  shopping-cart-microservice:
#    image: my-habitat/shopping-cart-microservice
#    links:
#      - mysql
#      - logstash
#      - inventory-microservice
#      - product-microservice
#      - cache-infrastructure
#    depends_on:
#      - mysql
#      - logstash
#    expose:
#      - "8084"
#  order-microservice:
#    image: my-habitat/order-microservice
#    links:
#      - mysql
#      - logstash
#    depends_on:
#      - mysql
#      - logstash
#      - shopping-cart-microservice
#      - inventory-microservice
#    expose:
#      - "8090"
#  monitor-dashboard:
#    image: my-habitat/monitor-dashboard
#    ports:
#      - "9100:9100"
#    links:
#      - logstash
#    depends_on:
#      - logstash
  api-gateway:
    image: my-habitat/api-gateway
    ports:
      - "8787:8787"
    environment:
      - JAVA_OPTS="-Xms128m -Xmx256m"
    links:
      - keycloak-server
#      - inventory-microservice
      - device-microservice
#      - shopping-cart-microservice
#      - order-microservice
      - account-microservice
      - room-microservice
      - logstash
    extra_hosts:
      - "dockernet:${EXTERNAL_IP}"
